name: Auto-build HTML

on: 
  push: 
      branches:
          - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Build
      working-directory: ./
      run: |
        echo "installing asciidoctor"
        sudo apt-get install asciidoctor ruby -y
        echo "Making deployment dir - docs/"
        mkdir docs
        echo "Add README to docs/"
        asciidoctor README.adoc -o docs/index.html
        echo "Add supermodel to docs/"
        asciidoctor supermodel.adoc -o docs/supermodel.html
        sed -i 's#img src="#img src="https://nicholascar.com/qsi-supermodel/#' docs/supermodel.html
        echo "Add supermodel RDF to docs/"
        cp rdf/*.ttl docs/
        echo "Add images to docs/"
        cp -r images docs/
        echo "Backbone Model"
        mkdir doc/backbone
        cp backbone/model.ttl doc/backbone/model.ttl
        echo "QSI Place Names Model"
        mkdir doc/placenames
        asciidoctor placenames/placenames.adoc -o doc/placenames/index.html
        cp placenames/*.ttl doc/placenames/
        cp placenames/*.png doc/placenames/
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
         BRANCH: gh-pages
         FOLDER: docs